apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: argocd-health-check
  namespace: argocd
spec:
  default:
    checkIntervalSec: 30
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 2
    
    logConfig:
      enabled: true

    config:
      type: TCP
      tcpHealthCheck:
        port: 8080
  
  targetRef:
    group: ""
    kind: Service
    name: argocd-server
