apiVersion: v1
kind: ResourceQuota
metadata:
  name: gke-critical-pods
  namespace: istio-system
spec:
  hard:
    pods: "1G" 
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-node-critical
      - system-cluster-critical
