apiVersion: v2
name: observability-stack
description: The LGTM Stack
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: 80.10.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki
    version: 6.49.0
    repository: https://grafana.github.io/helm-charts
  - name: tempo
    version: 1.24.1
    repository: https://grafana.github.io/helm-charts
