apiVersion: v2
name: istio-ambient
version: 1.0.0
dependencies:
  - name: base
    version: 1.24.0
    repository: https://istio-release.storage.googleapis.com/charts
  
  - name: cni
    version: 1.24.0
    repository: https://istio-release.storage.googleapis.com/charts

  - name: istiod
    version: 1.24.0
    repository: https://istio-release.storage.googleapis.com/charts

  - name: ztunnel
    version: 1.24.0
    repository: https://istio-release.storage.googleapis.com/charts
