apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: opentelemetry-demo
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: "0.39.0"
    helm:
      values: |
          # We use our own components, so disable the bundled ones to save CPU/RAM
          prometheus:
            enabled: false
          grafana:
            enabled: false
          jaeger:
            enabled: false
          
          opentelemetry-collector:
          config:
            exporters:
              otlp:
                endpoint: "observability-stack-tempo.monitoring.svc.cluster.local:4317" 
                tls:
                  insecure: true

  destination:
    server: https://kubernetes.default.svc
    namespace: otel-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
