apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: sre-portfolio-platform
      auth:
        workloadIdentity:
          clusterLocation: us-central1-a
          clusterName: sre-portfolio-cluster
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
